{% set name = "mimesis" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 044ac378c61db0e06832ff722548fd6e604881d36bc938002e0bd5b85eeb6a98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - mimesis
    - mimesis.builtins
    - mimesis.data
    - mimesis.data.int
    - mimesis.providers

about:
  home: https://github.com/lk-geimfari/mimesis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Mimesis: fake data generator.'
  doc_url: https://mimesis.readthedocs.io/
  dev_url: https://github.com/lk-geimfari/mimesis

extra:
  recipe-maintainers:
    - utabe
    - janjagusch
