{% set name = "mimesis" %}
{% set version = "16.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Using github sdist to include upstream tests.
  url: https://github.com/lk-geimfari/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c79d6b3b1b476e195cfabe5990605584dd8526c9718ae4675b0db5c2bda8e333

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - mimesis
    - mimesis.builtins
    - mimesis.data
    - mimesis.data.int
    - mimesis.providers

about:
  home: https://github.com/lk-geimfari/mimesis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Mimesis: fake data generator.'
  doc_url: https://mimesis.readthedocs.io/
  dev_url: https://github.com/lk-geimfari/mimesis

extra:
  recipe-maintainers:
    - utabe
    - janjagusch
