{% set name = "mimesis" %}
{% set version = "16.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Using github sdist to include upstream tests.
  url: https://github.com/lk-geimfari/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c79d6b3b1b476e195cfabe5990605584dd8526c9718ae4675b0db5c2bda8e333

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
  run_constrained:
    - factory-boy >=3.3.0
    - pytest >=7.2

test:
  source_files:
    - tests
    - minifier.py
  requires:
    - pip
    - pytest >=7.2
    - colorama >=0.4.6  # test_minifier.py
    - pytest-mock >=3.10  # [not (osx and x86 and py>311)]
    - pytz >=2023.3  # test_providers/test_datetime.py
    - pytest-randomly >=3.15.0  # test_schema.py: test_field_reseed with MissingSeed
  commands:
    - pip check
    # test_factory requires factory-boy
    # test_internet.py requires validators >=0.20
    - pytest tests --ignore="tests/test_plugins/test_factory" --ignore="tests/test_providers/test_internet.py" # [not (osx and x86 and py>311)]
    - pytest tests --ignore="tests/test_plugins/test_factory" --ignore="tests/test_providers/test_internet.py" --ignore="test_builtins/test_usa_spec.py" # [osx and x86 and py>311]
  imports:
    - mimesis
    - mimesis.builtins
    - mimesis.providers
    - mimesis.datasets

about:
  home: https://github.com/lk-geimfari/mimesis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fake data generator.
  description: |
    Mimesis is a powerful Python library that empowers developers to
    generate massive amounts of synthetic data efficiently.
  doc_url: https://mimesis.readthedocs.io/
  dev_url: https://github.com/lk-geimfari/mimesis

extra:
  recipe-maintainers:
    - utabe
    - janjagusch
